title: APS portfolio on OTT streaming services
description: Some of the most innovative internet services are OTT platforms. This portfolio examines and evaluates the features offered by over-the-top (OTT) platforms, as well as the time and space efficiency of the algorithms used to execute the various features.
show_downloads: false
google_analytics:
theme: jekyll-theme-minimal
markdown: kramdown
